# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdata',
            name='bank_id',
            field=models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, to='bank.BankData'),
        ),
    ]
